import { EmotionKey, EmotionDetail } from 'types/emotion';
import {
  Angry,
  Anxious,
  Comfortable,
  Flutter,
  Funny,
  Gloomy,
  Happy,
  Lonely,
  Proud,
  Pleased,
  Sad,
  Tired,
} from 'assets/emotion';

export const EMOTIONS: Record<EmotionKey, EmotionDetail> = {
  happy: {
    icon: <Happy width={60} height={60} />,
    color: 'bg-orange_gradient',
    noun: '행복',
    label: '행복한',
    value: 'happy',
  },
  good: {
    icon: <Pleased width={60} height={60} />,
    color: 'bg-orange_gradient',
    noun: '기분좋음',
    label: '기분좋은',
    value: 'good',
  },
  joyful: {
    icon: <Funny width={60} height={60} />,
    color: 'bg-yellow_gradient',
    noun: '즐거움',
    label: '즐거운',
    value: 'joyful',
  },
  excited: {
    icon: <Flutter width={60} height={60} />,
    color: 'bg-yellow_gradient',
    noun: '설렘',
    label: '설레는',
    value: 'excited',
  },
  proud: {
    icon: <Proud width={60} height={60} />,
    color: 'bg-green_gradient',
    noun: '뿌듯',
    label: '뿌듯한',
    value: 'proud',
  },
  calm: {
    icon: <Comfortable width={60} height={60} />,
    color: 'bg-green_gradient',
    noun: '편안',
    label: '편안한',
    value: 'calm',
  },
  tired: {
    icon: <Tired width={60} height={60} />,
    color: 'bg-purple_gradient',
    noun: '피곤',
    label: '피곤한',
    value: 'tired',
  },
  lonely: {
    icon: <Lonely width={60} height={60} />,
    color: 'bg-purple_gradient',
    noun: '외로움',
    label: '외로운',
    value: 'lonely',
  },
  sad: {
    icon: <Sad width={60} height={60} />,
    color: 'bg-blue_gradient',
    noun: '슬픔',
    label: '슬픈',
    value: 'sad',
  },
  down: {
    icon: <Gloomy width={60} height={60} />,
    color: 'bg-blue_gradient',
    noun: '우울',
    label: '우울한',
    value: 'down',
  },
  worried: {
    icon: <Anxious width={60} height={60} />,
    color: 'bg-red_gradient',
    noun: '불안',
    label: '불안한',
    value: 'worried',
  },
  angry: {
    icon: <Angry width={60} height={60} />,
    color: 'bg-red_gradient',
    noun: '화남',
    label: '화난',
    value: 'angry',
  },
};
